name: Benchmark
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        docker run -v $(pwd):/checkout -w /checkout ruby:slim sh -c "\
          apt-get update && \
          apt install -y cimg-dev libmagickwand-dev libvips42 wget build-essential git && \
          mkdir /ruby && \
          wget -O- https://cache.ruby-lang.org/pub/ruby/\$RUBY_MAJOR/ruby-\$RUBY_VERSION.tar.gz | tar xzC /ruby --strip-components=1 && \
          bundle install --no-cache && \
          ruby extconf.rb && \
          make clean && \
          make && \
          bundle exec rake benchmark"
      timeout-minutes: 5
