# this isn't a "recommended minimal setup"
#   it includes stuff needed for the benchmark (for example, CImg for phamilie), i.e. for the competing gems
#   also installing gcc and c++ might be slower due to the "linux-headers" package

name: Benchmark
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: alpine
      run: |
        docker run --rm -v $(pwd):/checkout -w /checkout ruby:alpine sh -c "\
          wget -O /usr/local/include/CImg.h https://raw.githubusercontent.com/GreycLab/CImg/3d1fc212ffe933cb2bc841e504920e5a67e676b8/CImg.h && \
          apk add --no-cache git build-base linux-headers imagemagick-dev vips vips-tools && \
          bundle install --no-cache && \
          ruby extconf.rb && make clean && make && \
          bundle exec rake benchmark"
      timeout-minutes: 5

    - name: slim provision the container
      run: docker build -t dhash-vips-benchmark-slim -f benchmark.slim.Dockerfile .
      timeout-minutes: 5
    - name: slim prepare and run rake
      run: |
        docker run --rm -v $(pwd):/checkout -w /checkout dhash-vips-benchmark-slim \
          sh -c "bundle install --no-cache && ruby extconf.rb && make clean && make && bundle exec rake benchmark"
      timeout-minutes: 5
