name: Docker Image
on:
  push:
    tags:
    - "v*.*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo ::set-env name=DHASH_VIPS_VERSION::$(echo "$GITHUB_REF" | rev | cut -dv -f1 | rev)
    - run: docker build . -f Dockerfile -t dhash-vips:$GITHUB_SHA --build-arg DHASH_VIPS_VERSION
